apiVersion: v1
kind: Service
metadata:
  name: generic-genai-app-nlq
spec:
  type: {{ .Values.c3po.service.type }}
  selector:
    app.kubernetes.io/name: generic-genai-app-nlq
  ports:
    - name: http
      port: {{ .Values.env.AGENT_BASE_PORT }}
      targetPort: 8000
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800