apiVersion: v1
kind: Service
metadata:
  name: commercial-us-sbx-iidd-genai-precanned-deck
spec:
  type: {{ .Values.c3po.service.type }}
  selector:
    app.kubernetes.io/name: commercial-us-sbx-iidd-genai-precanned-deck
  ports:
    - name: http
      port: {{ .Values.env.AGENT_BASE_PORT }}
      targetPort: 8000
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800