apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.service_account.name }}
  namespace: {{ .Values.env.EKS_NAMESPACE }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.service_account.role }}
